Repository ingresse/android-sdk, pull requests merged in 2019-11, with the labels that each got.

#109 Release/0.13.1
  sdk/build.gradle
  sdk/src/main/java/com/ingresse/sdk/model/response/UserTicketsJSON.kt
  sdk/src/main/java/com/ingresse/sdk/request/Phone.kt
  sdk/src/main/java/com/ingresse/sdk/services/PhoneService.kt
Labels: bugfix, mobile

#115 Release/0.14.0
  sdk/build.gradle
  sdk/src/main/java/com/ingresse/sdk/IngresseService.kt
  sdk/src/main/java/com/ingresse/sdk/base/IngresseSocketCallback.kt
  sdk/src/main/java/com/ingresse/sdk/base/IngresseWebsocketListener.kt
  sdk/src/main/java/com/ingresse/sdk/base/SocketResponse.kt
  sdk/src/main/java/com/ingresse/sdk/builders/URLBuilder.kt
  sdk/src/main/java/com/ingresse/sdk/helper/Constants.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/WebSocketTransactionDataJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/EntranceReportJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/ExternalGroupJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/InternalItemsJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/ItemJSON.kt
  sdk/src/main/java/com/ingresse/sdk/request/Report.kt
  sdk/src/main/java/com/ingresse/sdk/services/EntranceReportService.kt
  sdk/src/main/java/com/ingresse/sdk/services/TransferService.kt
  sdk/src/main/java/com/ingresse/sdk/services/UserService.kt
  sdk/src/main/java/com/ingresse/sdk/services/WebSocketService.kt
Labels: feature, mobile

#106 Create new request to get entrance report
  sdk/src/main/java/com/ingresse/sdk/IngresseService.kt
  sdk/src/main/java/com/ingresse/sdk/builders/URLBuilder.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/EntranceReportJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/ExternalGroupJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/InternalItemsJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/entranceReport/ItemJSON.kt
  sdk/src/main/java/com/ingresse/sdk/request/Report.kt
  sdk/src/main/java/com/ingresse/sdk/services/EntranceReportService.kt
Labels: bravo, feature, mobile, tested, to deploy

#116 Release/0.14.1
  sdk/build.gradle
  sdk/src/main/java/com/ingresse/sdk/builders/ClientBuilder.kt
  sdk/src/main/java/com/ingresse/sdk/services/POSService.kt
Labels: feature, mobile

#113 Increase timeout
  sdk/src/main/java/com/ingresse/sdk/builders/ClientBuilder.kt
  sdk/src/main/java/com/ingresse/sdk/services/POSService.kt
Labels: tested, to deploy
