Repository ingresse/android-sdk, pull requests merged in 2019-10, with the labels that each got.

#102 Release/0.12.1
  sdk/build.gradle
  sdk/src/main/java/com/ingresse/sdk/services/EntranceService.kt
Labels: mobile

#107 Release/0.12.2
  sdk/build.gradle
  sdk/src/main/java/com/ingresse/sdk/model/response/PlannerAttributesJSON.kt
Labels: bugfix, mobile

#101 Change JSON response for nullable
  sdk/src/main/java/com/ingresse/sdk/model/response/PlannerAttributesJSON.kt
Labels: bugfix
