Repository ingresse/android-sdk, pull requests merged in 2020-01, with the labels that each got.

#105 Add ddi on responses and add country list request
  sdk/src/main/java/com/ingresse/sdk/IngresseService.kt
  sdk/src/main/java/com/ingresse/sdk/builders/URLBuilder.kt
  sdk/src/main/java/com/ingresse/sdk/model/request/UserBasicInfos.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/CountryJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/PlannerAttributesJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/TransactionsJSON.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/UserDataJSON.kt
  sdk/src/main/java/com/ingresse/sdk/request/Phone.kt
  sdk/src/main/java/com/ingresse/sdk/services/PhoneService.kt
Labels: alfa, feature, mobile

#52 Add event details request
  sdk/src/main/java/com/ingresse/sdk/IngresseService.kt
  sdk/src/main/java/com/ingresse/sdk/model/request/EventDetailsRequest.kt
  sdk/src/main/java/com/ingresse/sdk/model/response/EventDetailsJSON.kt
  sdk/src/main/java/com/ingresse/sdk/request/EventDetails.kt
  sdk/src/main/java/com/ingresse/sdk/services/EventDetailsService.kt
Labels: feature, tested, to deploy

#72 Add canceled callback in event list call
  sdk/src/main/java/com/ingresse/sdk/helper/Constants.kt
  sdk/src/main/java/com/ingresse/sdk/services/EventService.kt
Labels: tested, to deploy
